### ISSUE TITLE
Archive links doesnt works anymore

### ISSUE THREAD

**Issue by Mattias16-beep** [oppositelocks/Contabo-Windows10#1]
Hello sir,

This was the tuto i really needed but as soon as i typed the link.. i've seen that the url provided isnt valid anymore.. 

Do you have a solution maybe ? Thanks

**Comment by Mattias16-beep** [comment]
found another link here.. i'm just trying it RN 

https://mde1.androidfilehost.com/dl/6Qhf2gTdNsIx996pegAvPw/1733929570/4279422670115708683/windows10.gz

**Comment by oppositelocks** [comment]
Try this link:
https://archive.org/download/windows10_202406/windows10.gz

This particular image already contains the required drivers, so not all images found on the internet will work.

**Comment by Mattias16-beep** [comment]
Thanks you so much for your fast reply !!! 

But I don't know why does it takes so much times? ? ? 

Don't you think it's possible to DL the file and put it into another file host ? 

![image](https://github.com/user-attachments/assets/31fde109-5a31-4ab2-8ce1-04a8fa8af75d)

**Comment by oppositelocks** [comment]
The connection is pretty limited with archive.org but it's easy to upload and share a direct link.  For the amount of downloads it's not really worth the effort to use another file host.

**Comment by Mattias16-beep** [comment]
I have to set up 10+ machines.. so i'm currently downloading the .gz on my machine to put it on my current ubuntu VPS. It'll be certainly faster in my case. 

Anyway thanks for the readme without you I think I would already abandoned the projet :D 

I let u know if the .gz u gave me is working. Thanks you again.
